# DristChat config

permission_global: "dchat.feature.messages" # checked before displaying any message
permission_global_prefix: "dchat.feature.prefix" # checked before displaying DM+ prefixes
permission_global_suffix: "dchat.feature.suffix" # checked before displaying DM+ suffixes
permission_global_sound: "dchat.feature.sound" # sound on global messages
global_message_sound: "UI_BUTTON_CLICK" # global messages sound
global_sound_volume: 2.0 # global messages sound volume
global_sound_pitch: 1.0 # global messages sound pitch
global_animation_offset: 12 #global offset before animation
global_animation_delay: 10 # global offset between frames
global_prefix_placeholder: "%dc_prefix_parsed%"
global_suffix_placeholder: "%dc_suffix_parsed%"

message_format:
  message: "%prefix%%sender%%suffix%: %message%"
  color: "ffffff"
  decoration: "null"
# permission for translation - dchat.translation.<language>

private_messages:
  message: "(%prefix%%sender%%suffix% -> %prefix%%receiver%%suffix%): %message%"
  color: "555555"
  decoration: "ITALIC"
  sound: "ENTITY_CHICKEN_EGG"

player_first_joined:
  message: "[++] %sender% has joined the game for the first time!"
  sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
  color: "00aa00"
  decoration: "BOLD"
  permission: "dchat.feature.joinleave"
player_joined:
  message: "[+] %prefix%%sender%%%suffix%"
  sound: "UI_BUTTON_CLICK"
  color: "ffff55"
  decoration: "BOLD"
  permission: "dchat.feature.joinleave"
player_left:
  message: "[-] %prefix%%sender%%%suffix%"
  sound: "UI_BUTTON_CLICK"
  color: "ffff55"
  decoration: "BOLD"
  permission: "dchat.feature.joinleave"

title_on_join:
  header: # supports animation
    - "&2W&aelcome!"
    - "&aW&2e&alcome!"
    - "&aWe&2l&acome!"
    - "&aWel&2c&aome!"
    - "&aWelc&2o&ame!"
    - "&aWelco&2m&ae!"
    - "&aWelcom&2e&a!"
    - "&aWelcome&2!"
  footer: # supports animation
    - "DristMine classic"
  color: "null"
  decoration: "null"
  permission: "dchat.feature.title"
actionbar_on_join:
  message: # supports animation
    - "Welcome to DristMine!"
  color: "ffaa00"
  decoration: "UNDERLINED"
  permission: "dchat.feature.actionbar"
sound_on_join:
  sound: "ENTITY_PLAYER_LEVELUP"
  permission: "dchat.feature.joinsound"

advancements:
  message: "%message%"
  color: "55ff55"
  decoration: "BOLD"
  permission: "dchat.feature.advancements"

deaths:
  message: "%message%"
  color: "ff5555"
  decoration: "BOLD"
  permission: "dchat.feature.deaths"