name: DristChat
version: '${version}'
main: dristmine.dristchat.DristChat
api-version: '1.20'
author: Mjakot
description: Paper plugin for toggleable custom chat supporting player prefixes, notifications and more!
website: https://github.com/mjakot/DristChat
