name: DristChat
version: '${version}'
main: dristmine.dristchat.DristChat
api-version: '1.20'
author: Mjakot
description: Toggleable bukkit chat plugin for dristmine mc server
website: https://github.com/mjakot/DristChat
